NODE_ENV: "production"
HTTPPORT: 8080
ACCESS_TOKEN_SECRET: ""
REFRESH_TOKEN_SECRET: ""
FORGOTTEN_PASSWORD_SECRET: ""

runtime: nodejs
service: api

env: flex
automatic_scaling:
  max_num_instances: 1

env_variables:
  NODE_ENV: "production"
  HTTPPORT: 8080
  ACCESS_TOKEN_SECRET: ""
  REFRESH_TOKEN_SECRET: ""
  FORGOTTEN_PASSWORD_SECRET: ""
